spring.application.name=crud-empleados-api
spring.profiles.default=dev
server.port=${SERVER_PORT:8080}

# Aplicación
management.endpoints.web.exposure.include=health,info

# Credenciales Basic Auth externas
app.security.admin-username=${ADMIN_USERNAME:admin}
app.security.admin-password=${ADMIN_PASSWORD:admin123}

# Datasource PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:empleados}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
